sudo: required
dist: trusty

language: java
jdk:
  - openjdk8
  - oraclejdk8

git:
  submodules: false
before_install: git submodule update --init --recursive

install: ./gradlew setupDecompWorkspace
script: ./gradlew build

notifications:
  email: false
